name: CI
# thanks for @mpariente for copying this workflow
# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  src-test:
    name: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade --user pip --quiet
        python -m pip install coverage codecov --upgrade-strategy only-if-needed --quiet
        python -m pip install -e .['tests, torch']
        python --version
        pip --version
        python -m pip list
    - name: Source code tests
      run: |
        coverage run -a -m py.test tests

    # - name: CLI tests
    #   run: |
    #     chmod +x ./tests/cli_test.sh
    #     ./tests/cli_test.sh

    - name: Coverage report
      run: |
        coverage report -m
        coverage xml -o coverage.xml
    - name: Codecov upload
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml